apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox
    env: local
spec:
  containers:
    - name: busybox-pod
      image: busybox
      command: ['echo', 'Hello from Pod']
  restartPolicy: Never