apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  initContainers:
    - name: init-service
      image:  busybox
      command: ['sh', '-c', 'echo "Initializing..."; sleep 5;']
      volumeMounts:
        - name: workdir
          mountPath: /work
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: workdir
      emptyDir: {}
