apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
    - name: resource-pod
      image: nginx
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"