apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: secret-pod
    image: busybox
    command: ['sh', '-c', 'echo "Password is: $APP_PASSWORD" && sleep 3600']
    env:
      - name:  APP_PASSWORD
        valueFrom:
          secretKeyRef:
            name:  app-secret
            key:  APP_PASSWORD
  restartPolicy: Never