apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:
  containers:
    # -----------------------
    # Main application
    # -----------------------
    - name: app-container
      image: busybox:1.36
      command: ["sh", "-c", "while true; do echo 'Hello from app' >> /var/log/app.log; sleep 2; done"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log

    # -----------------------
    # Sidecar container (log processor)
    # -----------------------
    - name: log-sidecar
      image: busybox:1.36
      command: ["sh", "-c", "tail -F /var/log/app.log"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log

  volumes:
    - name: log-volume
      emptyDir: {}
