kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-role-binding
  namespace: apache

subjects:
- kind: User
  name:  sa-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name:  devops-grp
  apiGroup: rbac.authorization.k8s.io

